group: deprecated-2017Q2

language: python

python:
  - "2.7"
  - "3.5"

cache: pip

env:
  - MPLBACKEND=agg

notifications:
  email: false

services:
  - docker

addons:
  apt:
    sources:
    - sourceline: "deb http://build.openmodelica.org/apt `lsb_release -cs` stable"
      key_url: "http://build.openmodelica.org/apt/openmodelica.asc"
    packages:
    - omc
    - omlib-modelica-3.2.?
    - tidy

before_install:
  - chmod +x buildingspy/tests/MyModelicaLibrary/Resources/Scripts/travis/bin/dymola
  - cp buildingspy/tests/MyModelicaLibrary/Resources/Scripts/travis/bin/dymola $HOME/bin/
  - chmod +x buildingspy/tests/MyModelicaLibrary/Resources/Scripts/travis/bin/jm_ipython.sh
  - cp buildingspy/tests/MyModelicaLibrary/Resources/Scripts/travis/bin/jm_ipython.sh $HOME/bin/
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker pull "$DOCKER_USERNAME"/travis_ubuntu-1604_dymola-2018fd01-x86_64
  - docker pull "$DOCKER_USERNAME"/ubuntu-1604_jmodelica_trunk

install:
  - python -m pip install --upgrade pip setuptools wheel
  - python -m pip install --upgrade --only-binary=numpy,scipy,matplotlib numpy scipy matplotlib==2.1.0
  - python -m pip install --upgrade autopep8
  - python -m pip install .

# Execute tests
script:
  - omc --version
  - make pep8 PEP8_CORRECT_CODE=true
#  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then make doctest; fi
  - make unittest
