language: python
python:
  - "2.7"

notifications:
  email: false

git:
  depth: 3

services:
  - docker

# Enable system site packages in virtualenv so BuildingsPy sees scipy and matplotlib
virtualenv:
  system_site_packages: true

before_install:
  - sudo mv BuildingsPy/buildingspy/tests/MyModelicaLibrary/Resources/Scripts/travis/usr/local/bin/dymola /usr/local/bin/
  - sudo chmod +x /usr/local/bin/dymola
  - sudo apt-get install -qq python-numpy python-scipy python-matplotlib
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker pull "$DOCKER_USERNAME"/travis_ubuntu-1604_dymola-2017fd01-x86-64

# Execute tests
script:
  - (cd BuildingsPy && make doctest unittest)
