dist: trusty
language: python
python:
  - "2.7"
#  - "3.4"
#  - "3.5"
#  - "3.6"

cache: pip

env:
  - MPLBACKEND=agg

notifications:
  email: false

git:
  depth: 3

services:
  - docker

addons:
  apt:
    sources:
    - sourceline: "deb http://build.openmodelica.org/apt `lsb_release -cs` stable"
      key_url: "http://build.openmodelica.org/apt/openmodelica.asc"
    packages:
    - omc
    - omlib-modelica-3.2.?
    - tidy

before_install:
  - sudo mv buildingspy/tests/MyModelicaLibrary/Resources/Scripts/travis/usr/local/bin/dymola /usr/local/bin/
  - sudo chmod +x /usr/local/bin/dymola
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker pull "$DOCKER_USERNAME"/travis_ubuntu-1604_dymola-2017fd01-x86-64

install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy,matplotlib numpy scipy matplotlib
  - pip install future gitpython pytidylib autopep8
  - pip install .

# Execute tests
script:
  - omc --version
  - autopep8 --in-place --recursive --max-line-length=200 --exclude="*/thirdParty/*" --select="E225,W291,W293" buildingspy; git diff --exit-code .
  - make doctest unittest
