language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
before_install:
  - sudo apt-get install -y python-scipy tidy
install:
  - pip install future gitpython pytidylib
# command to run tests
script: make doctest
