language: python
python:
  - "2.7"
  - "3.5"
notifications:
  email: false
# command to install dependencies
addons:
  apt:
    packages:
    - python-scipy
    - tidy
install:
  - pip install scipy future gitpython pytidylib
# command to run tests
script: make doctest
